source 'https://rubygems.org'
source 'https://rails-assets.org'
ruby '2.1.2'

gem 'active_model_serializers'
gem 'analytics-ruby', '<1.0'
gem 'aws-sdk', '~> 1.0'
gem 'bootstrap-sass'
gem 'bourbon'
gem 'bugsnag'
gem 'cancan'
gem 'coffee-script'
gem 'connection_pool'
gem 'countries'
gem 'country_select'
gem 'customerio'
gem 'curb'
gem 'devise', github: 'plataformatec/devise', branch: 'lm-rails-4-2'
gem 'draper'
gem 'elasticsearch-model', git: 'git://github.com/elasticsearch/elasticsearch-rails.git', ref: '304615e5c548448e95cdbca29de197b5a789d0d3'
gem 'elasticsearch-rails', git: 'git://github.com/elasticsearch/elasticsearch-rails.git', ref: '304615e5c548448e95cdbca29de197b5a789d0d3'
gem 'font_assets'
gem 'friendly_id', github: 'norman/friendly_id'
gem 'gemoji', github: 'github/gemoji'
gem 'gibbon'
gem 'git'
gem 'github-markdown'
gem 'hogan_assets'
gem 'html-pipeline'
gem 'htmlentities'
gem 'jquery-rails'
gem 'kaminari'
gem 'bootstrap-kaminari-views'
gem 'leftronic'
gem 'librato-rails'
gem 'lograge'
gem 'markerb'
gem 'multi_fetch_fragments'
gem 'mustache'
gem 'omniauth-facebook', '1.4.0' # http://stackoverflow.com/questions/11597130/omniauth-facebook-keeps-reporting-invalid-credentials
gem 'omniauth-twitter'
gem 'omniauth-github'
# gem 'oink'
gem 'paperclip'
gem 'pg'
gem 'pghero'
gem 'puma'
gem 'pusher'
gem 'premailer-rails'
gem 'rack-streaming-proxy'
gem 'rails', '4.2.0.beta1'
gem 'rails-assets-backbone',            '1.0.0'
gem 'rails-assets-dropzone',            '3.9.0'
gem 'rails-assets-ink',                 '1.0.5'
gem 'rails-assets-jquery-autosize',     '1.18.9'
gem 'rails-assets-jquery-cookie',       '1.4.0'
gem 'rails-assets-jquery-textcomplete', '0.1.4'
gem 'rails-assets-marked',              '0.3.2'
gem 'rails-assets-moment',              '2.5.0'
gem 'rails-assets-normalize-css',       '2.1.3'
gem 'rails-assets-notify.js',           '1.2.0'
gem 'rails-assets-nprogress',           '0.1.6'
gem 'rails-assets-numeral',             '1.5.3'
gem 'rails-assets-jquery-timeago'
gem 'rails-assets-jquery.inview',       '1.0.0'
gem 'rails-assets-spin.js',             '2.0.1'
gem 'rails-assets-underscore',          '1.5.2'
gem 'rails_stdout_logging', group: [:development, :production]
gem 'react-rails', '~> 0.10.0.0'
gem 'redcarpet'
gem 'redis'
gem 'responders', '~> 2.0'
gem 'rinku'
gem 'sanitize'
gem 'sass-rails', '5.0.0.beta1'
gem 'sequenced', '~> 1.5.0'
gem 'sidekiq'
gem 'skylight', '~> 0.3.19'
gem 'split', :require => 'split/dashboard'
gem 'stripe'
gem 'uglifier'
gem 'warden', "~> 1.2.3"
gem 'workflow'
gem 'zeroclipboard-rails'

group :development, :test do
  gem 'active_record_query_trace'
  # gem 'debugger' # enable once ruby 2.1.1 is supported
  gem 'email_spec'
  # gem "letter_opener"
  gem 'machinist', '~> 2'
  gem 'pry'
  gem 'quiet_assets'
  gem 'rspec-rails'
  gem 'terminal-table'
  gem 'timecop'
  gem 'ffaker'
  gem 'syntax'
  gem 'fakeweb'
  gem 'rest_client'
  gem 'teaspoon'
end

group :development do
  # gem 'rack-mini-profiler'
  # gem 'sql-logging'
  # gem 'ruby-prof'
  # gem 'stackprof'
end

group :test do
  gem 'autotest-standalone'
  gem 'codeclimate-test-reporter', require: nil
  gem 'simplecov'
  gem 'vcr'
  gem 'webmock'
end

group :production do
  gem 'dalli'
  gem 'memcachier'
  gem 'newrelic_rpm'
  gem 'rails_12factor'
end
